Json tabbed code sample
xetorthio/jedis pull request #3895
Opened 2024-07-16 13:21 UTC by andy-stark-redis

Code samples for the two JSON pages:
https://redis.io/docs/latest/develop/data-types/json/
https://redis.io/docs/latest/develop/data-types/json/path/

2024-07-16 13:47 UTC, sazzad16 commented
@bsbodden Would it be a sane ask to split the long Strings?

2024-07-16 14:11 UTC, bsbodden commented
> @bsbodden Would it be a sane ask to split the long Strings?

Agreed, good idea

2024-07-17 11:06 UTC, sazzad16 requested changes

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            )
```suggestion
            new Path2("$..mountain_bikes[?(@.price < 3000 && @.specs.weight < 10)]")
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$..[?(@.specs.material == 'alloy')].model")
```suggestion
            "bikes:inventory", new Path2("$..[?(@.specs.material == 'alloy')].model")
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$..[?(@.specs.material =~ '(?i)al')].model")
```suggestion
            "bikes:inventory", new Path2("$..[?(@.specs.material =~ '(?i)al')].model")
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$.inventory.mountain_bikes[0].regex_pat"),
```suggestion
            "bikes:inventory", new Path2("$.inventory.mountain_bikes[0].regex_pat"),
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$.inventory.mountain_bikes[1].regex_pat"),
```suggestion
            "bikes:inventory", new Path2("$.inventory.mountain_bikes[1].regex_pat"),
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$.inventory.mountain_bikes[2].regex_pat"),
```suggestion
            "bikes:inventory", new Path2("$.inventory.mountain_bikes[2].regex_pat"),
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        Object res39 = jedis.jsonGet("bikes:inventory", new Path2("$..price"));
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        Object res40 = jedis.jsonNumIncrBy("bikes:inventory", new Path2("$..price"), -100);
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        Object res41 = jedis.jsonNumIncrBy("bikes:inventory", new Path2("$..price"), 100);
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        jedis.jsonSet("bikes:inventory", new Path2("$.inventory.*[?(@.price<2000)].price"), 1500);
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        Object res42 = jedis.jsonGet("bikes:inventory", new Path2("$..price"));
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            new Path2("$.inventory.*[?(@.price<2000)].colors"),
```suggestion
            "bikes:inventory", new Path2("$.inventory.*[?(@.price<2000)].colors"),
```

2024-07-17 11:06 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +        );
```suggestion
        Object res44 = jedis.jsonGet("bikes:inventory", new Path2("$..[*].colors"));
```

2024-07-17 11:33 UTC, sazzad16 commented on src/test/java/io/redis/examples/JsonExample.java
> +            "Prickett", "Royce", "Castilla"
```suggestion
            "riders", new Path2("$"), 1, "Prickett", "Royce", "Castilla"
```

2024-07-17 12:10 UTC, merged